// MoonHighlight — Node.js binding entry point
// Auto-generated by tree-sitter generate
// This file provides the Node.js API for the MoonBit grammar

const Parser = require('tree-sitter');
const path = require('path');

// Dynamically load the native parser module
try {
  const binding = require('./moonhighlight.node');
  module.exports = {
    language: Parser.Language.load(binding),
    // Convenience: parse a string and return the syntax tree
    parse(source, options = {}) {
      const parser = new Parser();
      parser.setLanguage(this.language);
      return parser.parse(source, options);
    },
    // Get node type names for debugging
    get nodeTypeNames() {
      return this.language._nodeTypes || [];
    },
  };
} catch (e) {
  // Fallback when native module not built yet
  console.warn('[moonhighlight] Native parser not found. Run `npm run install:node` to build.');
  module.exports = null;
}